"""Canonical filesystem locations used across the project.

Distinguishes two location classes so a PyInstaller release works cleanly:

* **Read-only bundled data** (decks, glosses, fonts) - resolved from the
  package directory at dev time, from ``sys._MEIPASS`` at runtime.
* **Writable user state** (stats, settings, high scores) - ``%APPDATA%/KanjiRe``
  on Windows, ``~/.kanjire`` elsewhere, so it survives across releases.
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

_IS_FROZEN = getattr(sys, "frozen", False) and hasattr(sys, "_MEIPASS")

if _IS_FROZEN:
    # PyInstaller temp-extracts the bundle here at runtime.
    PACKAGE_DIR = Path(sys._MEIPASS) / "kanjire"  # type: ignore[attr-defined]
else:
    PACKAGE_DIR = Path(__file__).resolve().parent

PROJECT_ROOT = PACKAGE_DIR.parent

DATA_DIR = PACKAGE_DIR / "data"
#: Self-contained vocabulary database (read-only at runtime, generated by
#: ``scripts/build_jlpt_dataset.py``).
DB_PATH = DATA_DIR / "kanjire.db"

#: Where raw text files for corpus ingestion are kept by convention.
CORPORA_DIR = PROJECT_ROOT / "corpora"


def _user_dir() -> Path:
    """Return a writable per-user data directory.

    Frozen builds *must* write outside the (temp) bundle; dev runs keep things
    inside ``kanjire/data/`` for easy inspection."""
    if _IS_FROZEN or os.environ.get("KANJIRE_USER_DIR"):
        if env := os.environ.get("KANJIRE_USER_DIR"):
            return Path(env)
        if appdata := os.environ.get("APPDATA"):
            return Path(appdata) / "KanjiRe"
        return Path.home() / ".kanjire"
    return DATA_DIR


USER_DIR = _user_dir()
USER_DIR.mkdir(parents=True, exist_ok=True)

#: Per-user state file: high scores, last-used menu settings, audio toggles,
#: persisted locale and saved custom-mode presets.
USER_STATE_PATH = USER_DIR / "user_state.json"

#: Per-user knowledge stats. Kept in its *own* SQLite file so updating the
#: bundled vocabulary deck never wipes the player's progress.
STATS_DB_PATH = USER_DIR / "stats.db"
